included:
  - MyProject/**/*.swift

trailing_whitespace:
  ignores_empty_lines: true

type_name:
  max_length:
    warning: 10000
    error: 100000
  min_length:
    warning: 0
    error: 0

identifier_name:
  max_length:
    warning: 10000
    error: 100000
  min_length:
    warning: 0
    error: 0

function_parameter_count:
    warning: 8
    error: 10

override_in_extension:
  severity: error

superfluous_disable_command:
  severity: warning

disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - identifier_name
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting
  - number_separator
  - todo
  - type_body_length
  - unused_closure_parameter
  - no_space_in_method_call

opt_in_rules:
  - anyobject_protocol
  - array_init
  - balanced_xctest_lifecycle
  - capture_variable
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - empty_count
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - explicit_self
  - fallthrough
  - first_where
  - flatmap_over_map_reduce
  - force_try
  - force_unwrapping
  - ibinspectable_in_extension
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - modifier_order
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - prefer_zero_over_explicit_init
  - quick_discouraged_call
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - trailing_comma
  - unneeded_break_in_switch
  - unused_enumerated
  - unused_import
  - valid_ibinspectable
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition
